#!/usr/bin/env bash

vol-update() {
	eww update getvolsym=$(~/scripts/volume -s)
}

volbar-update() {
	eww open volumebar
	sleep 2
	eww close volumebar
}

case "$1" in
	-u) vol-update;;
	-b) volbar-update;;
esac
