#!/usr/bin/env sh

help() {
	echo '	-c,			copy selection'
	echo '	-s,			save selection'
}

areacopy() {	
	grim -g "$(slurp -w "0" -b "#191a1a75")" - | wl-copy;
	wl-paste -t image/png > /tmp/screenshot.png
	notify-send -i /tmp/screenshot.png 'Screenshot' 'Selection Copied'
	mpv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
}

areasave() {
	grim -g "$(slurp -w "0" -b "#191a1a75")" /mnt/SSD/Images/Screenshots/$(date +'%s_grim.png');
	notify-send -i /mnt/SSD/Images/Screenshots/$(date +'%s_grim.png') 'Screenshot' 'Selection Saved'
	mpv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
}

case "$1" in
	-c) areacopy;;
	-s) areasave;;
	*) help;;
esac
