#!/usr/bin/env sh

help() {
	echo '	-i,			install packages from main repos'
	echo '	-p,			install paru'
	echo '	-a,			install packages from aur'
	echo '	-c,			copy files to proper places'
}

paruinstall() {
	sudo pacman -S --needed base-devel
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si
}

pkgsinstall() {
	sudo pacman -S \
	\ # Display Manager
		lightdm \
	\ # Window Manager
		awesome \
	\ # Terminal App Stuff
		wget \
		neovim \
		nsxiv \
		zathura \
		rofi \
		numlockx \
		bottom \
		maim \
		xclip \
		mpv \
		wine-staging \
		fontconfig \
	\ # General
		alacritty \
		emacs \
		firefox \
		thunar \
		thunar-archive-plugin \
		thunar-volman \
		tumbler \
		gvfs \
		discord \
		pavucontrol \
		blueman \
		lxappearance \
		solaar \
		papirus-icon-theme \
	\ # Art Stuff
		krita \
		blender \
	\ # Audio Stuff
		sound-theme-freedesktop \
		musescore \
		yabridge \
		yabridgectl \
		carla \
		calf \
		easyeffects \
	\ # Game Stuff
		steam \
		retroarch \
		godot \
	\ # Fonts
		noto-fonts \
		noto-fonts-cjk \
		noto-fonts-emoji
}

aurinstall() {
	paru -S --skipreview \
	\ # Display Greeter
		lightdm-mini-greeter \
	\ # Terminal App Stuff
		nitch \
		picom-allusive \
		joshuto-bin \
		shell-color-scripts \
		cbonsai \
		discocss-git \
	\ # General
		nvim-packer-git \
		spotify \
		orchis-theme \
		phinger-cursors \
		vial-appimage \
	\ # Music Stuff
		bitwig-studio \
	\ # Game Stuff
		prismlauncher \
		heroic-games-launcher-bin \
		# rpcs3-git \
		soundux \
	\ # Fonts
		ttf-comfortaa \
		otf-symbola \
		ttf-victor-mono
}

copyfiles() {
	git clone https://github.com/Chiivo/arch-dotfiles.git
	cp -r ./arch-dotfiles/.config .config
	cp -r ./arch-dotfiles/scripts ./
	cp -r ./arch-dotfiles/.bashrc ./
}

bling() {
	git clone https://github.com/BlingCorp/bling.git
	cp bling .config/awesome/
}

case "$1" in
	-i) pkgsinstall;;
	-p) paruinstall;;
	-a) aurinstall;;
	-c) copyfiles;;
	*) help;;
esac
