#!/usr/bin/env sh

help() {
	echo '	-p,			install paru'
	echo '	-i,			install packages from main repos'
	echo '	-a,			install packages from aur'
	echo '	-c,			copy files to proper places'
}

paruinstall() {
	sudo pacman -S --needed base-devel
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si
}

pkgsinstall() {
	sudo pacman -S \
		`# Display Manager` \
		sddm \
		\
		`# Window Manager` \
		awesome \
		\
		`# Drivers` \
		nvidia \
		\
		`# Terminal Stuff` \
		xorg-xrdb \
		xorg-xinput \
		wget \
		neovim \
		nsxiv \
		zathura \
		rofi \
		bottom \
		maim \
		xclip \
		mpv \
		wine-staging \
		fontconfig \
		man-db \
		\
		`# General` \
		alacritty \
		emacs \
		firefox \
		thunar \
		thunar-archive-plugin \
		file-roller\
		thunar-volman \
		tumbler \
		gvfs \
		pavucontrol \
		blueman \
		lxappearance \
		solaar \
		papirus-icon-theme \
		\
		`# Art Stuff` \
		krita \
		blender \
		\
		`# Audio Stuff` \
		pipewire-pulse \
		pipewire-alsa \
		pipewire-jack \
		alsa-utils \
		sound-theme-freedesktop \
		musescore \
		yabridge \
		yabridgectl \
		carla \
		calf \
		easyeffects \
		\
		`# Game Stuff` \
		steam \
		retroarch \
		godot \
		\
		`# Fonts` \
		noto-fonts \
		noto-fonts-cjk \
		noto-fonts-emoji
}

aurinstall() {
	paru -S --skipreview \
		`# Display Greeter` \
		sddm-sugar-candy-git \
		\
		`# Display Manager Stuff` \
		awesome-bling-git \
		\
		`# Terminal Stuff` \
		nitch \
		picom-allusive \
		joshuto-bin \
		shell-color-scripts \
		cbonsai \
		vencord-desktop-git \
		\
		`# General` \
		nvim-packer-git \
		spotify \
		orchis-theme \
		phinger-cursors \
		vial-appimage \
		\
		`# Music Stuff` \
		bitwig-studio \
		\
		`# Game Stuff` \
		prismlauncher \
		heroic-games-launcher-bin \
		\
		`# rpcs3-git` \
		soundux \
		`# Fonts` \
		ttf-comfortaa \
		otf-symbola \
		ttf-victor-mono
}

copyfiles() {
	cp -r ./arch-dotfiles/.config/ ./
	cp -r ./arch-dotfiles/scripts/ ./
	cp -r ./arch-dotfiles/fonts/ ./.local/share/
	cp -r ./arch-dotfiles/.bashrc ./
	cp -r ./arch-dotfiles/.Xresources ./
}

enableservices() {
	sudo systemctl enable --now sddm
	sudo systemctl enable --now bluetooth
}

case "$1" in
	-i) pkgsinstall;;
	-p) paruinstall;;
	-a) aurinstall;;
	-c) copyfiles;;
	*) help;;
esac
